# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8ebc90c851eb2a1a5a701694ec39635f5e21455bcc80388e5129108f24a436713e4093803b2ba3a1913e1b46feabf33e7a2ebc6a4dc5b1f1e995c0cdd6f39a4

test:
  secret_key_base: a9478d637c8ddb718bc03490a47321294474ff47ab538a7dcfd0d3a84fce47ede2843b6894375a6ef675116ace360aafe37f600747ae864b6b8ddeffa55f84fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
